#!/usr/bin/env node
/**
 * Generate apps/web/src/styles/tokens.css and tailwind-theme.css from tokens.json.
 *
 *   node packages/ui-tokens/build.mjs          # write
 *   node packages/ui-tokens/build.mjs --check  # CI: fail if generated files are stale
 *
 * Themes: :root = light, [data-theme="dark"] = control-room dark. Legacy variable names are
 * emitted as aliases so pre-v2 CSS keeps rendering during the migration.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..", "..");
const tokens = JSON.parse(readFileSync(join(here, "tokens.json"), "utf8"));
const outDir = join(root, "apps", "web", "src", "styles");

const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, "$1-$2").replace(/\./g, "\\.").toLowerCase();

function themeVars(t) {
  const lines = [];
  for (const [k, v] of Object.entries(t.neutral)) lines.push(`--neutral-${k}: ${v};`);
  for (const key of [
    "canvas", "surface", "surfaceSunken", "surfaceRaised", "border", "borderStrong", "text", "textMuted",
    "textSubtle", "grid", "accent", "accentPress", "accentTint", "accentText", "focusRing",
    "equipmentStroke", "equipmentFill", "equipmentFillRunning", "scrim",
  ]) {
    lines.push(`--${kebab(key)}: ${t[key]};`);
  }
  for (const [k, v] of Object.entries(t.status)) lines.push(`--status-${kebab(k)}: ${v};`);
  for (const [k, v] of Object.entries(t.medium)) lines.push(`--medium-${kebab(k)}: ${v};`);
  for (const [k, v] of Object.entries(t.shadow)) lines.push(`--shadow-${k}: ${v};`);
  return lines;
}

function staticVars() {
  const lines = [];
  for (const [p, def] of Object.entries(tokens.alarmPriority)) {
    if (p.startsWith("$")) continue;
    lines.push(`--priority-${p.toLowerCase()}: var(--status-${kebab(def.status)});`);
    lines.push(`--priority-${p.toLowerCase()}-tint: var(--status-${kebab(def.status)}-tint);`);
  }
  for (const [k, v] of Object.entries(tokens.mediumDash)) {
    if (k.startsWith("$")) continue;
    lines.push(`--medium-${kebab(k)}-dash: ${v};`);
  }
  for (const [k, v] of Object.entries(tokens.radius)) lines.push(`--radius-${k}: ${v};`);
  for (const [k, v] of Object.entries(tokens.space)) lines.push(`--space-${kebab(k)}: ${v};`);
  for (const [k, v] of Object.entries(tokens.zIndex)) lines.push(`--z-${k}: ${v};`);
  lines.push(`--font-sans: ${tokens.font.sans};`, `--font-mono: ${tokens.font.mono};`);
  for (const [k, v] of Object.entries(tokens.type)) {
    lines.push(`--type-${k}-size: ${v.size};`, `--type-${k}-lh: ${v.lh};`, `--type-${k}-weight: ${v.weight};`,
      `--type-${k}-tracking: ${v.tracking};`);
  }
  for (const [k, v] of Object.entries(tokens.motion)) lines.push(`--motion-${k}: ${v};`);
  for (const [k, v] of Object.entries(tokens.layout)) lines.push(`--layout-${kebab(k)}: ${v};`);
  return lines;
}

// Pre-v2 names used across existing CSS → v2 semantics.
const LEGACY_ALIASES = {
  "--ink-900": "var(--text)", "--ink-700": "var(--neutral-700)", "--ink-500": "var(--text-muted)",
  "--ink-300": "var(--text-subtle)", "--line": "var(--border)", "--line-strong": "var(--border-strong)",
  "--inverse": "var(--surface)", "--bg": "var(--canvas)", "--border-subtle": "var(--border)",
  "--surface-muted": "var(--surface-sunken)", "--surface-elevated": "var(--surface-raised)",
  "--accent-dim": "var(--accent-tint)", "--accent-hover": "var(--accent-press)", "--accent2": "var(--status-high)",
  "--advisory": "var(--status-high)", "--advisory-tint": "var(--status-high-tint)",
  "--warning": "var(--status-high)", "--warning-tint": "var(--status-high-tint)",
  "--critical": "var(--status-critical)", "--critical-tint": "var(--status-critical-tint)",
  "--healthy": "var(--status-healthy)", "--status-warning": "var(--status-high)",
  "--status-warning-fill": "var(--status-high-tint)", "--status-critical-fill": "var(--status-critical-tint)",
  "--status-sensor-fill": "var(--status-sensor-bad-tint)", "--status-unknown": "var(--text-muted)",
  "--space-xs": "var(--space-1)", "--space-sm": "var(--space-2)", "--space-md": "var(--space-3)",
  "--space-lg": "var(--space-4)", "--space-xl": "var(--space-6)", "--space-2xl": "var(--space-8)",
  "--space-3xl": "var(--space-12)", "--space-4xl": "var(--space-16)",
  "--radius": "var(--radius-lg)", "--radius-dialog": "var(--radius-lg)",
  "--shadow-sm": "var(--shadow-e1)", "--shadow-md": "var(--shadow-e2)",
  "--z-strip": "var(--z-sticky)", "--z-toolbar": "var(--z-sidebar)", "--z-overlay": "var(--z-modal)",
  "--font-ui": "var(--font-sans)", "--font-data": "var(--font-mono)",
  "--motion-abnormal-pulse": "1.8s",
};

const indent = (lines) => lines.map((l) => `  ${l}`).join("\n");
const header = "/* GENERATED by packages/ui-tokens/build.mjs from tokens.json — do not edit by hand. */\n";

const tokensCss = `${header}
:root {
  color-scheme: light;
${indent(themeVars(tokens.themes.light))}
${indent(staticVars())}

  /* Legacy aliases (pre-v2 CSS) */
${indent(Object.entries(LEGACY_ALIASES).map(([k, v]) => `${k}: ${v};`))}
}

:root[data-theme="dark"] {
  color-scheme: dark;
${indent(themeVars(tokens.themes.dark))}
}
`;

// Tailwind v4: map utilities onto the runtime variables so both themes work.
const twColor = (name, v) => `--color-${name}: var(${v});`;
const twLines = [
  twColor("canvas", "--canvas"), twColor("surface", "--surface"), twColor("surface-sunken", "--surface-sunken"),
  twColor("surface-raised", "--surface-raised"), twColor("border", "--border"),
  twColor("border-strong", "--border-strong"), twColor("text", "--text"), twColor("text-muted", "--text-muted"),
  twColor("text-subtle", "--text-subtle"), twColor("accent", "--accent"), twColor("accent-press", "--accent-press"),
  twColor("accent-tint", "--accent-tint"),
  ...Object.keys(tokens.themes.light.neutral).map((k) => twColor(`neutral-${k}`, `--neutral-${k}`)),
  ...Object.keys(tokens.themes.light.status).map((k) => twColor(`status-${kebab(k)}`, `--status-${kebab(k)}`)),
  ...Object.keys(tokens.themes.light.medium).map((k) => twColor(`medium-${kebab(k)}`, `--medium-${kebab(k)}`)),
  // legacy utility names used by existing components
  twColor("ink-900", "--text"), twColor("ink-700", "--neutral-700"), twColor("ink-500", "--text-muted"),
  twColor("ink-300", "--text-subtle"), twColor("line", "--border"), twColor("line-strong", "--border-strong"),
  twColor("inverse", "--surface"), twColor("advisory", "--status-high"), twColor("advisory-tint", "--status-high-tint"),
  twColor("warning", "--status-high"), twColor("warning-tint", "--status-high-tint"),
  twColor("critical", "--status-critical"), twColor("critical-tint", "--status-critical-tint"),
  twColor("healthy", "--status-healthy"),
  ...Object.keys(tokens.radius).map((k) => `--radius-${k}: var(--radius-${k});`),
  "--shadow-e1: var(--shadow-e1);", "--shadow-e2: var(--shadow-e2);", "--shadow-e3: var(--shadow-e3);",
  "--font-sans: var(--font-sans);", "--font-mono: var(--font-mono);",
];
const twCss = `${header}/* reference: do not emit variables (tokens.css owns them); inline: utilities use var(--x) directly. */
@theme inline reference {
${indent(twLines)}
}
`;

const outputs = [
  [join(outDir, "tokens.css"), tokensCss],
  [join(outDir, "tailwind-theme.css"), twCss],
];

const check = process.argv.includes("--check");
let stale = 0;
for (const [path, content] of outputs) {
  if (check) {
    let current = "";
    try { current = readFileSync(path, "utf8"); } catch { /* missing */ }
    if (current !== content) {
      console.error(`stale: ${path} — run pnpm tokens:build`);
      stale++;
    }
  } else {
    writeFileSync(path, content);
    console.log(`wrote ${path}`);
  }
}
process.exit(stale ? 1 : 0);
