#!/usr/bin/env python3
"""Generate packages/sample-data/component-library/standard_components.json."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "packages" / "sample-data" / "component-library" / "standard_components.json"


def svg(icon_id: str, accent: str = "#1CC8FF") -> str:
    """Deterministic low-poly inline SVG per component kind."""
    shapes = {
        "power_supply": f'<rect x="8" y="14" width="48" height="36" rx="4" fill="#0E1A2A" stroke="{accent}" stroke-width="2"/><path d="M20 32h12l-6-12 6 24 6-18h12" fill="none" stroke="{accent}" stroke-width="2"/>',
        "converter": f'<polygon points="32,8 56,32 32,56 8,32" fill="#0E1A2A" stroke="{accent}" stroke-width="2"/><line x1="16" y1="32" x2="48" y2="32" stroke="{accent}" stroke-width="2"/>',
        "battery": f'<rect x="10" y="18" width="44" height="28" rx="3" fill="#0E1A2A" stroke="{accent}" stroke-width="2"/><rect x="54" y="26" width="6" height="12" fill="{accent}"/><line x1="18" y1="32" x2="46" y2="32" stroke="{accent}" stroke-width="2"/>',
        "fuse": f'<rect x="14" y="12" width="36" height="40" rx="2" fill="#0E1A2A" stroke="{accent}" stroke-width="2"/><line x1="32" y1="16" x2="32" y2="48" stroke="#F59E0B" stroke-width="3"/>',
        "relay": f'<rect x="10" y="16" width="44" height="32" rx="4" fill="#0E1A2A" stroke="{accent}" stroke-width="2"/><circle cx="24" cy="32" r="6" fill="none" stroke="{accent}" stroke-width="2"/><rect x="36" y="26" width="12" height="12" fill="{accent}" opacity="0.4"/>',
        "plc_do": f'<rect x="8" y="12" width="48" height="40" rx="3" fill="#0E1A2A" stroke="{accent}" stroke-width="2"/><rect x="14" y="20" width="8" height="8" fill="#2DD4BF"/><rect x="26" y="20" width="8" height="8" fill="#2DD4BF"/><rect x="38" y="20" width="8" height="8" fill="#EF4444"/>',
        "plc_ai": f'<rect x="8" y="12" width="48" height="40" rx="3" fill="#0E1A2A" stroke="{accent}" stroke-width="2"/><path d="M14 40 L22 28 L30 36 L38 22 L46 40" fill="none" stroke="#8B5CF6" stroke-width="2"/>',
        "plc_di": f'<rect x="8" y="12" width="48" height="40" rx="3" fill="#0E1A2A" stroke="{accent}" stroke-width="2"/><rect x="14" y="28" width="8" height="8" fill="none" stroke="#2DD4BF" stroke-width="2"/><rect x="26" y="28" width="8" height="8" fill="none" stroke="#2DD4BF" stroke-width="2"/><rect x="38" y="28" width="8" height="8" fill="none" stroke="#2DD4BF" stroke-width="2"/>',
        "motor": f'<circle cx="32" cy="32" r="20" fill="#0E1A2A" stroke="{accent}" stroke-width="2"/><circle cx="32" cy="32" r="6" fill="{accent}"/><line x1="32" y1="12" x2="32" y2="20" stroke="{accent}" stroke-width="2"/><line x1="32" y1="44" x2="32" y2="52" stroke="{accent}" stroke-width="2"/>',
        "fan": f'<circle cx="32" cy="32" r="18" fill="none" stroke="{accent}" stroke-width="2"/><path d="M32 14 Q42 32 32 50 Q22 32 32 14" fill="{accent}" opacity="0.3"/><circle cx="32" cy="32" r="4" fill="{accent}"/>',
        "blower": f'<rect x="12" y="20" width="40" height="24" rx="2" fill="#0E1A2A" stroke="{accent}" stroke-width="2"/><polygon points="52,32 60,24 60,40" fill="{accent}"/><circle cx="24" cy="32" r="8" fill="none" stroke="{accent}" stroke-width="2"/>',
        "pump": f'<circle cx="28" cy="32" r="16" fill="#0E1A2A" stroke="{accent}" stroke-width="2"/><polygon points="44,24 56,32 44,40" fill="{accent}"/><line x1="20" y1="32" x2="8" y2="32" stroke="{accent}" stroke-width="2"/>',
        "valve": f'<rect x="20" y="14" width="24" height="36" rx="2" fill="#0E1A2A" stroke="{accent}" stroke-width="2"/><polygon points="32,8 40,18 24,18" fill="{accent}"/><line x1="8" y1="32" x2="20" y2="32" stroke="{accent}" stroke-width="2"/><line x1="44" y1="32" x2="56" y2="32" stroke="{accent}" stroke-width="2"/>',
        "coupling": f'<circle cx="20" cy="32" r="10" fill="#0E1A2A" stroke="{accent}" stroke-width="2"/><circle cx="44" cy="32" r="10" fill="#0E1A2A" stroke="{accent}" stroke-width="2"/><rect x="28" y="28" width="8" height="8" fill="{accent}"/>',
        "bearing": f'<rect x="14" y="14" width="36" height="36" rx="4" fill="#0E1A2A" stroke="{accent}" stroke-width="2"/><circle cx="32" cy="32" r="12" fill="none" stroke="{accent}" stroke-width="2"/><circle cx="32" cy="32" r="4" fill="{accent}"/>',
        "duct": f'<rect x="8" y="24" width="48" height="16" rx="2" fill="#0E1A2A" stroke="{accent}" stroke-width="2"/><polygon points="56,32 64,26 64,38" fill="{accent}" opacity="0.5"/>',
        "pipe": f'<rect x="8" y="28" width="48" height="8" rx="4" fill="#0E1A2A" stroke="{accent}" stroke-width="2"/><circle cx="8" cy="32" r="4" fill="{accent}"/><circle cx="56" cy="32" r="4" fill="{accent}"/>',
        "tank": f'<rect x="16" y="20" width="32" height="32" rx="2" fill="#0E1A2A" stroke="{accent}" stroke-width="2"/><line x1="16" y1="36" x2="48" y2="36" stroke="{accent}" stroke-width="1" opacity="0.5"/>',
        "filter": f'<rect x="14" y="16" width="36" height="32" rx="2" fill="#0E1A2A" stroke="{accent}" stroke-width="2"/><line x1="20" y1="22" x2="44" y2="42" stroke="#F59E0B" stroke-width="1"/><line x1="44" y1="22" x2="20" y2="42" stroke="#F59E0B" stroke-width="1"/>',
        "current_sensor": f'<rect x="12" y="18" width="40" height="28" rx="3" fill="#0E1A2A" stroke="{accent}" stroke-width="2"/><path d="M20 32 C26 24 30 40 36 32" fill="none" stroke="#8B5CF6" stroke-width="2"/>',
        "voltage_sensor": f'<rect x="12" y="18" width="40" height="28" rx="3" fill="#0E1A2A" stroke="{accent}" stroke-width="2"/><path d="M18 38 L24 22 L30 38 L36 26" fill="none" stroke="#8B5CF6" stroke-width="2"/>',
        "rpm_sensor": f'<circle cx="32" cy="32" r="18" fill="#0E1A2A" stroke="{accent}" stroke-width="2"/><text x="32" y="36" text-anchor="middle" fill="{accent}" font-size="10" font-family="monospace">RPM</text>',
        "vibration_sensor": f'<rect x="14" y="20" width="36" height="24" rx="2" fill="#0E1A2A" stroke="{accent}" stroke-width="2"/><path d="M16 32 L22 26 L28 38 L34 28 L40 36 L46 30" fill="none" stroke="#EF4444" stroke-width="2"/>',
        "temp_sensor": f'<circle cx="32" cy="28" r="12" fill="#0E1A2A" stroke="{accent}" stroke-width="2"/><rect x="29" y="38" width="6" height="14" fill="{accent}"/>',
        "airflow_sensor": f'<path d="M16 40 Q32 16 48 40" fill="none" stroke="{accent}" stroke-width="2"/><line x1="24" y1="32" x2="40" y2="32" stroke="#8B5CF6" stroke-width="2"/>',
        "pressure_sensor": f'<circle cx="32" cy="32" r="16" fill="#0E1A2A" stroke="{accent}" stroke-width="2"/><line x1="32" y1="16" x2="32" y2="8" stroke="{accent}" stroke-width="2"/><text x="32" y="36" text-anchor="middle" fill="{accent}" font-size="9">PSI</text>',
        "limit_switch": f'<rect x="16" y="20" width="32" height="24" rx="2" fill="#0E1A2A" stroke="{accent}" stroke-width="2"/><circle cx="32" cy="32" r="6" fill="#2DD4BF"/>',
    }
    body = shapes.get(icon_id, f'<rect x="12" y="12" width="40" height="40" fill="#0E1A2A" stroke="{accent}" stroke-width="2"/>')
    return (
        f'<svg viewBox="0 0 64 64" xmlns="http://www.w3.org/2000/svg">'
        f'<rect width="64" height="64" fill="#08111F" rx="6"/>'
        f"{body}</svg>"
    )


def port(
    port_id: str,
    name: str,
    direction: str,
    medium: str,
    quantity_kind: str,
    *,
    required: bool = True,
    compat: list[str] | None = None,
    nominal_min: float | None = None,
    nominal_max: float | None = None,
) -> dict:
    return {
        "port_id": port_id,
        "name": name,
        "direction": direction,
        "medium": medium,
        "quantity_kind": quantity_kind,
        "nominal_range": {"min": nominal_min, "max": nominal_max},
        "compatibility_tags": compat or [],
        "required": required,
    }


def signal(
    signal_id: str,
    name: str,
    quantity_kind: str,
    unit: str,
    source_port_id: str,
    *,
    expected_min: float,
    expected_max: float,
    sampling_ms: int = 500,
    quality: str = "GOOD",
    weight: float = 0.8,
    alarm_high: float | None = None,
    alarm_low: float | None = None,
) -> dict:
    thresholds: dict = {}
    if alarm_high is not None:
        thresholds["high"] = alarm_high
    if alarm_low is not None:
        thresholds["low"] = alarm_low
    return {
        "signal_template_id": signal_id,
        "name": name,
        "quantity_kind": quantity_kind,
        "unit": unit,
        "expected_min": expected_min,
        "expected_max": expected_max,
        "sampling_hint_ms": sampling_ms,
        "quality_required": quality,
        "source_port_id": source_port_id,
        "evidence_weight_default": weight,
        "alarm_thresholds": thresholds,
    }


def fault(
    fault_id: str,
    title: str,
    description: str,
    severity: str,
    actions: list[str],
    *,
    required_evidence: list[dict] | None = None,
    optional_evidence: list[dict] | None = None,
    downstream: list[str] | None = None,
    safety: str = "caution",
) -> dict:
    return {
        "fault_mode_id": fault_id,
        "title": title,
        "description": description,
        "severity": severity,
        "root_asset_applicability": "self",
        "required_evidence": required_evidence or [],
        "optional_evidence": optional_evidence or [],
        "downstream_effects": downstream or [],
        "rejected_alternatives": [],
        "operator_actions": actions,
        "safety_level": safety,
    }


def ev(signal_id: str, relation: str, *, weight: float = 0.9, required: bool = True) -> dict:
    return {
        "signal_template_id": signal_id,
        "relation": relation,
        "weight": weight,
        "required": required,
    }


def visual(
    icon_id: str,
    *,
    accent_role: str,
    node_shape: str,
    low_poly: str,
    preview: str,
    port_layout: dict,
    size: tuple[int, int] = (180, 96),
) -> dict:
    accent_map = {
        "power": "#1CC8FF",
        "actuation": "#2DD4BF",
        "process": "#8B5CF6",
        "sensor": "#F59E0B",
        "safety": "#EF4444",
    }
    accent = accent_map.get(accent_role, "#1CC8FF")
    return {
        "icon_kind": "inline_svg",
        "icon_svg": svg(icon_id, accent),
        "node_shape": node_shape,
        "low_poly_shape": low_poly,
        "accent_role": accent_role,
        "port_layout": port_layout,
        "size_hint": {"width": size[0], "height": size[1]},
        "preview_label": preview,
        "render_tokens": {
            "base": "industrial_dark",
            "accent": f"{accent_role}_cyan" if accent_role == "power" else f"{accent_role}_accent",
            "danger": "fault_red",
        },
    }


def component(**kwargs) -> dict:
    base = {
        "version": "1.0.0",
        "manufacturer_neutral": True,
        "tags": [],
        "recommended_sensors": [],
        "hmi_render_hint": {"card_style": "industrial_compact", "show_ports": True},
        "safety_notes": [],
        "limits": {},
    }
    base.update(kwargs)
    return base


def build_library() -> dict:
    components = [
        component(
            component_type_id="dc_power_supply",
            display_name="DC Power Supply",
            category="power_electrical",
            description="Regulated DC bus supply for bench and small-plant loads.",
            physical_domain="electrical",
            tags=["power", "dc", "supply"],
            ports=[
                port("ac_in", "AC Input", "input", "ac_power", "voltage", nominal_min=100, nominal_max=240),
                port("dc_out", "DC Output", "output", "dc_power", "voltage", compat=["dc_12v", "dc_24v"], nominal_min=11, nominal_max=13.5),
                port("sense_out", "Sense Output", "output", "analog_signal", "voltage"),
            ],
            signal_templates=[
                signal("supply_voltage", "Supply Voltage", "voltage", "V", "sense_out", expected_min=11.5, expected_max=12.5, alarm_low=11.0, alarm_high=13.0),
                signal("supply_current", "Supply Current", "current", "A", "dc_out", expected_min=0, expected_max=10, alarm_high=9.5),
            ],
            fault_modes=[
                fault("voltage_sag", "Voltage Sag", "Output voltage drops below nominal under load.", "warning",
                      ["Measure load current and verify terminal torque.", "Reduce parallel loads before resetting supply."],
                      required_evidence=[ev("supply_voltage", "low")]),
                fault("overvoltage", "Overvoltage", "Output exceeds safe operating range.", "critical",
                      ["Isolate downstream loads immediately.", "Verify setpoint and regulator module before re-energizing."],
                      required_evidence=[ev("supply_voltage", "high")], safety="isolate_before_touch"),
                fault("unstable_supply", "Unstable Supply", "Voltage oscillates or hunts under steady load.", "warning",
                      ["Inspect input AC stability and DC filter capacitors.", "Check for intermittent ground path on output return."],
                      optional_evidence=[ev("supply_voltage", "noisy")]),
                fault("loose_terminal", "Loose Terminal", "Intermittent connection at output terminals.", "warning",
                      ["De-energize and re-torque output lugs to manufacturer spec.", "Inspect for heat discoloration at terminal block."],
                      optional_evidence=[ev("supply_voltage", "inconsistent")]),
            ],
            recommended_sensors=["voltage_sensor", "current_sensor"],
            safety_notes=["Verify polarity before connecting DC loads.", "Do not exceed rated output current."],
            limits={"max_output_current_a": 10, "nominal_voltage_v": 12},
            visual_asset=visual("power_supply", accent_role="power", node_shape="hex_card", low_poly="box_with_terminals",
                                preview="DC Supply", port_layout={"left": ["ac_in"], "right": ["dc_out", "sense_out"], "top": [], "bottom": ["mount"]}),
        ),
        component(
            component_type_id="dc_dc_converter",
            display_name="DC-DC Converter",
            category="power_electrical",
            description="Step-up or step-down DC conversion stage between bus segments.",
            physical_domain="electrical",
            tags=["power", "converter", "dc"],
            ports=[
                port("dc_in", "DC Input", "input", "dc_power", "voltage", nominal_min=10, nominal_max=48),
                port("dc_out", "DC Output", "output", "dc_power", "voltage", compat=["dc_12v", "dc_24v"]),
                port("enable_in", "Enable", "input", "digital_signal", "boolean_state", required=False),
            ],
            signal_templates=[
                signal("converter_input_v", "Input Voltage", "voltage", "V", "dc_in", expected_min=10, expected_max=48),
                signal("converter_output_v", "Output Voltage", "voltage", "V", "dc_out", expected_min=11, expected_max=13.5, alarm_low=10.5),
                signal("converter_efficiency", "Conversion Efficiency", "data", "%", "dc_out", expected_min=80, expected_max=98),
            ],
            fault_modes=[
                fault("input_undervoltage", "Input Undervoltage", "Input below minimum operating threshold.", "warning",
                      ["Verify upstream supply voltage and cable drop.", "Check input fuse and connector integrity."]),
                fault("output_regulation_fail", "Output Regulation Failure", "Output cannot maintain setpoint.", "critical",
                      ["Isolate load and measure output under no-load condition.", "Replace converter module if no-load voltage is out of spec."],
                      required_evidence=[ev("converter_output_v", "low")], safety="isolate_before_touch"),
                fault("thermal_shutdown", "Thermal Shutdown", "Converter shuts down due to overtemperature.", "warning",
                      ["Verify airflow around heat sink and ambient temperature.", "Reduce continuous load or add cooling path."]),
            ],
            recommended_sensors=["voltage_sensor", "current_sensor", "temperature_sensor"],
            limits={"max_input_v": 48, "max_output_a": 5},
            visual_asset=visual("converter", accent_role="power", node_shape="diamond_card", low_poly="prism_block",
                                preview="DC-DC", port_layout={"left": ["dc_in"], "right": ["dc_out"], "top": ["enable_in"], "bottom": ["mount"]}),
        ),
        component(
            component_type_id="battery_module",
            display_name="Battery Module",
            category="power_electrical",
            description="Energy storage module for ride-through and mobile bench setups.",
            physical_domain="electrical",
            tags=["power", "battery", "storage"],
            ports=[
                port("dc_out", "DC Output", "output", "dc_power", "voltage", compat=["dc_12v"]),
                port("charge_in", "Charge Input", "input", "dc_power", "voltage"),
                port("bms_data", "BMS Data", "bidirectional", "serial_comm", "data", required=False),
            ],
            signal_templates=[
                signal("battery_voltage", "Battery Voltage", "voltage", "V", "dc_out", expected_min=11.0, expected_max=13.2, alarm_low=11.5),
                signal("battery_soc", "State of Charge", "data", "%", "bms_data", expected_min=20, expected_max=100, alarm_low=15),
                signal("battery_temp", "Battery Temperature", "temperature", "C", "bms_data", expected_min=10, expected_max=45, alarm_high=40),
            ],
            fault_modes=[
                fault("cell_imbalance", "Cell Imbalance", "Individual cells drift outside balanced range.", "warning",
                      ["Run balance cycle per BMS procedure.", "Inspect for swollen cells before continued use."]),
                fault("low_soc", "Low State of Charge", "SOC below operational reserve.", "warning",
                      ["Reduce non-critical loads.", "Initiate controlled charge before next production run."],
                      required_evidence=[ev("battery_soc", "low")]),
                fault("thermal_runaway_risk", "Thermal Risk", "Battery temperature exceeds safe envelope.", "critical",
                      ["Isolate battery from load immediately.", "Move module to ventilated area and follow facility EHS protocol."],
                      required_evidence=[ev("battery_temp", "high")], safety="stop_required"),
            ],
            recommended_sensors=["voltage_sensor", "temperature_sensor"],
            safety_notes=["Do not short terminals.", "Use insulated tools when servicing."],
            limits={"nominal_voltage_v": 12, "capacity_ah": 50},
            visual_asset=visual("battery", accent_role="power", node_shape="rect_card", low_poly="box_with_terminals",
                                preview="Battery", port_layout={"left": ["charge_in"], "right": ["dc_out"], "top": ["bms_data"], "bottom": ["mount"]}),
        ),
        component(
            component_type_id="fuse_protection_block",
            display_name="Fuse Protection Block",
            category="power_electrical",
            description="Overcurrent protection between supply segments and loads.",
            physical_domain="electrical",
            tags=["protection", "fuse", "safety"],
            ports=[
                port("line_in", "Line In", "input", "dc_power", "current"),
                port("load_out", "Load Out", "output", "dc_power", "current"),
            ],
            signal_templates=[
                signal("fuse_current", "Fuse Current", "current", "A", "load_out", expected_min=0, expected_max=15, alarm_high=14),
            ],
            fault_modes=[
                fault("fuse_blown", "Blown Fuse", "Fuse element has opened due to overcurrent.", "critical",
                      ["Isolate upstream supply before replacing fuse.", "Investigate downstream short or locked rotor before re-energizing."],
                      required_evidence=[ev("fuse_current", "missing")], safety="isolate_before_touch"),
                fault("nuisance_trip", "Nuisance Opening", "Fuse opens under inrush without sustained fault.", "warning",
                      ["Verify fuse rating matches load inrush profile.", "Consider time-delay fuse class if inrush is legitimate."]),
            ],
            recommended_sensors=["current_sensor"],
            safety_notes=["Use correct fuse class and ampacity.", "Never bypass with wire or foil."],
            limits={"max_rating_a": 15},
            visual_asset=visual("fuse", accent_role="safety", node_shape="narrow_card", low_poly="fuse_block",
                                preview="Fuse", port_layout={"left": ["line_in"], "right": ["load_out"], "top": [], "bottom": []}),
        ),
        component(
            component_type_id="relay_contactor",
            display_name="Relay Contactor",
            category="power_electrical",
            description="Electromechanical switching for load enable and interlock paths.",
            physical_domain="electrical",
            tags=["relay", "switching", "control"],
            ports=[
                port("coil_in", "Coil Drive", "input", "digital_signal", "boolean_state"),
                port("contact_in", "Contact Input", "input", "dc_power", "current"),
                port("contact_out", "Contact Output", "output", "dc_power", "current"),
                port("aux_contact", "Auxiliary Contact", "output", "digital_signal", "boolean_state", required=False),
            ],
            signal_templates=[
                signal("coil_state", "Coil Energized", "boolean_state", "bool", "coil_in", expected_min=0, expected_max=1),
                signal("contact_current", "Contact Current", "current", "A", "contact_out", expected_min=0, expected_max=10),
            ],
            fault_modes=[
                fault("welded_contacts", "Welded Contacts", "Contacts remain closed when coil is de-energized.", "critical",
                      ["Isolate supply and verify contact state with meter.", "Replace contactor before returning to service."],
                      safety="isolate_before_touch"),
                fault("coil_open", "Open Coil", "Coil circuit failed; contactor will not pull in.", "warning",
                      ["Measure coil voltage at terminals during commanded ON.", "Inspect PLC output and wiring continuity."]),
            ],
            recommended_sensors=["current_sensor", "voltage_sensor"],
            limits={"max_contact_current_a": 10},
            visual_asset=visual("relay", accent_role="power", node_shape="rect_card", low_poly="contactor_box",
                                preview="Relay", port_layout={"left": ["coil_in", "contact_in"], "right": ["contact_out", "aux_contact"], "top": [], "bottom": ["mount"]}),
        ),
        component(
            component_type_id="plc_digital_output_module",
            display_name="PLC Digital Output Module",
            category="power_electrical",
            description="Digital output bank for enabling relays, valves, and indicator states.",
            physical_domain="electrical",
            tags=["plc", "digital", "output"],
            ports=[
                port("logic_in", "Logic Input", "input", "ethernet", "data"),
                port("do_ch1", "DO Channel 1", "output", "digital_signal", "boolean_state"),
                port("do_ch2", "DO Channel 2", "output", "digital_signal", "boolean_state", required=False),
            ],
            signal_templates=[
                signal("do_ch1_state", "DO Ch1 State", "boolean_state", "bool", "do_ch1", expected_min=0, expected_max=1),
                signal("do_ch2_state", "DO Ch2 State", "boolean_state", "bool", "do_ch2", expected_min=0, expected_max=1),
            ],
            fault_modes=[
                fault("output_stuck_high", "Output Stuck High", "Digital output remains ON when commanded OFF.", "critical",
                      ["Verify commanded state in PLC logic monitor.", "Isolate affected load before replacing output module."],
                      required_evidence=[ev("do_ch1_state", "stuck")]),
                fault("output_stuck_low", "Output Stuck Low", "Digital output will not energize when commanded ON.", "warning",
                      ["Check field wiring and load return path.", "Swap channel to confirm module vs wiring fault."]),
            ],
            recommended_sensors=[],
            limits={"channel_count": 8},
            visual_asset=visual("plc_do", accent_role="power", node_shape="rack_card", low_poly="io_module",
                                preview="PLC DO", port_layout={"left": ["logic_in"], "right": ["do_ch1", "do_ch2"], "top": [], "bottom": ["mount"]}),
        ),
        component(
            component_type_id="plc_analog_input_module",
            display_name="PLC Analog Input Module",
            category="power_electrical",
            description="Analog input bank for sensor scaling and thresholding.",
            physical_domain="electrical",
            tags=["plc", "analog", "input"],
            ports=[
                port("ai_ch1", "AI Channel 1", "input", "analog_signal", "data"),
                port("ai_ch2", "AI Channel 2", "input", "analog_signal", "data", required=False),
                port("logic_out", "Logic Bus", "bidirectional", "ethernet", "data"),
            ],
            signal_templates=[
                signal("ai_ch1_scaled", "AI Ch1 Scaled", "data", "unit", "ai_ch1", expected_min=0, expected_max=100),
                signal("ai_ch2_scaled", "AI Ch2 Scaled", "data", "unit", "ai_ch2", expected_min=0, expected_max=100),
            ],
            fault_modes=[
                fault("channel_saturation", "Input Saturation", "Analog input pegged at rail.", "warning",
                      ["Verify sensor wiring and excitation.", "Check scaling constants in PLC tag map."]),
                fault("channel_noise", "Excessive Noise", "Input signal noisy beyond filter capability.", "warning",
                      ["Inspect shield termination and ground loop.", "Relocate sensor cable away from power conductors."],
                      optional_evidence=[ev("ai_ch1_scaled", "noisy")]),
            ],
            recommended_sensors=[],
            limits={"resolution_bits": 16},
            visual_asset=visual("plc_ai", accent_role="power", node_shape="rack_card", low_poly="io_module",
                                preview="PLC AI", port_layout={"left": ["ai_ch1", "ai_ch2"], "right": ["logic_out"], "top": [], "bottom": ["mount"]}),
        ),
        component(
            component_type_id="plc_digital_input_module",
            display_name="PLC Digital Input Module",
            category="power_electrical",
            description="Digital input bank for tach pulses, limit switches, and discrete sensors.",
            physical_domain="electrical",
            tags=["plc", "digital", "input"],
            ports=[
                port("di_ch1", "DI Channel 1", "input", "digital_signal", "boolean_state"),
                port("di_ch2", "DI Channel 2", "input", "digital_signal", "boolean_state", required=False),
                port("logic_out", "Logic Bus", "bidirectional", "ethernet", "data"),
            ],
            signal_templates=[
                signal("di_ch1_state", "DI Ch1 State", "boolean_state", "bool", "di_ch1", expected_min=0, expected_max=1),
                signal("di_ch2_state", "DI Ch2 State", "boolean_state", "bool", "di_ch2", expected_min=0, expected_max=1),
            ],
            fault_modes=[
                fault("input_stuck_high", "Input Stuck High", "DI channel reads ON when field device is open.", "warning",
                      ["Verify field device contact type and wiring.", "Swap channel to isolate module fault."]),
                fault("input_stuck_low", "Input Stuck Low", "DI channel never energizes when field pulse is present.", "warning",
                      ["Measure pulse amplitude at module terminals.", "Check common return and surge protection."]),
            ],
            recommended_sensors=[],
            limits={"channel_count": 8},
            visual_asset=visual("plc_di", accent_role="power", node_shape="rack_card", low_poly="io_module",
                                preview="PLC DI", port_layout={"left": ["di_ch1", "di_ch2"], "right": ["logic_out"], "top": [], "bottom": ["mount"]}),
        ),
        component(
            component_type_id="dc_motor_12v",
            display_name="12V DC Motor",
            category="actuation_mechanical",
            description="Brushed DC motor for bench conveyor and fan drive applications.",
            physical_domain="electromechanical",
            tags=["motor", "dc", "actuation"],
            ports=[
                port("power_in", "Power Input", "input", "dc_power", "voltage", compat=["dc_12v"], nominal_min=11, nominal_max=13),
                port("shaft_out", "Shaft Output", "output", "mechanical_rotation", "rpm"),
                port("sense_out", "Sense Output", "output", "analog_signal", "current"),
            ],
            signal_templates=[
                signal("motor_current", "Motor Current", "current", "A", "sense_out", expected_min=0, expected_max=8, alarm_high=7.5),
                signal("motor_rpm", "Motor RPM", "rpm", "rpm", "shaft_out", expected_min=0, expected_max=3000, alarm_low=100),
                signal("motor_temperature", "Motor Temperature", "temperature", "C", "sense_out", expected_min=20, expected_max=85, alarm_high=75),
                signal("motor_vibration", "Motor Vibration", "vibration", "mm/s", "sense_out", expected_min=0, expected_max=10, alarm_high=7),
            ],
            fault_modes=[
                fault("mechanical_obstruction", "Mechanical Obstruction", "Rotor cannot turn freely due to jam.", "critical",
                      ["Isolate power and manually verify shaft rotation.", "Remove obstruction before re-energizing."],
                      required_evidence=[ev("motor_rpm", "low"), ev("motor_current", "high")], safety="isolate_before_touch"),
                fault("bearing_friction", "Bearing Friction", "Increased friction from worn bearing.", "warning",
                      ["Listen for grinding at low speed.", "Schedule bearing replacement before seizure."]),
                fault("undervoltage_stall", "Undervoltage Stall", "Motor stalls due to insufficient supply voltage.", "warning",
                      ["Measure supply at motor terminals under load.", "Verify cable gauge and connection integrity."],
                      required_evidence=[ev("motor_current", "high"), ev("motor_rpm", "low")]),
                fault("overcurrent", "Overcurrent", "Current exceeds continuous rating.", "critical",
                      ["Reduce mechanical load and verify free rotation.", "Check for shorted windings if no mechanical cause."],
                      required_evidence=[ev("motor_current", "high")], safety="isolate_before_touch"),
                fault("sensor_dropout", "Sensor Dropout", "RPM or current feedback missing.", "warning",
                      ["Inspect encoder or shunt wiring.", "Compare against redundant measurement if available."],
                      optional_evidence=[ev("motor_rpm", "missing")]),
            ],
            recommended_sensors=["current_sensor", "rpm_tachometer", "vibration_sensor", "temperature_sensor"],
            safety_notes=["Lock out drive before mechanical service.", "Keep fingers clear of rotating shaft."],
            limits={"nominal_voltage_v": 12, "max_current_a": 8, "max_rpm": 3000},
            visual_asset=visual("motor", accent_role="actuation", node_shape="hex_card", low_poly="cylinder_with_shaft",
                                preview="12V Motor", port_layout={"left": ["power_in"], "right": ["shaft_out", "sense_out"], "top": [], "bottom": ["mount"]}),
        ),
        component(
            component_type_id="bldc_fan",
            display_name="BLDC Fan",
            category="actuation_mechanical",
            description="Brushless fan for enclosure cooling and airflow circulation.",
            physical_domain="electromechanical",
            tags=["fan", "bldc", "cooling"],
            ports=[
                port("power_in", "Power Input", "input", "dc_power", "voltage", compat=["dc_12v", "dc_24v"]),
                port("pwm_in", "PWM Control", "input", "digital_signal", "data", required=False),
                port("air_out", "Air Outlet", "output", "airflow", "airflow"),
            ],
            signal_templates=[
                signal("fan_rpm", "Fan RPM", "rpm", "rpm", "air_out", expected_min=0, expected_max=4000, alarm_low=500),
                signal("fan_current", "Fan Current", "current", "A", "power_in", expected_min=0, expected_max=3, alarm_high=2.8),
                signal("fan_airflow", "Fan Airflow", "airflow", "CFM", "air_out", expected_min=0, expected_max=120, alarm_low=30),
            ],
            fault_modes=[
                fault("blade_obstruction", "Blade Obstruction", "Foreign material blocking blade path.", "critical",
                      ["Isolate power and inspect inlet guard.", "Remove debris before restart."],
                      required_evidence=[ev("fan_rpm", "low"), ev("fan_current", "high")], safety="isolate_before_touch"),
                fault("low_speed", "Low Speed", "Fan runs below commanded speed.", "warning",
                      ["Verify PWM command and supply voltage.", "Check for bearing drag or blade imbalance."]),
                fault("imbalance", "Blade Imbalance", "Vibration from uneven blade mass.", "warning",
                      ["Inspect blades for damage or buildup.", "Replace fan module if vibration persists."]),
                fault("coupling_slip", "Coupling Slip", "Drive coupling slips under load.", "warning",
                      ["Inspect set screw torque on hub.", "Verify shaft alignment with drive source."]),
                fault("airflow_degradation", "Airflow Degradation", "Delivered airflow below design.", "warning",
                      ["Check filter upstream restriction.", "Verify duct path is not collapsed or blocked."],
                      required_evidence=[ev("fan_airflow", "low")]),
            ],
            recommended_sensors=["rpm_tachometer", "current_sensor", "airflow_sensor"],
            limits={"max_rpm": 4000, "max_current_a": 3},
            visual_asset=visual("fan", accent_role="actuation", node_shape="circle_card", low_poly="disc_with_blades",
                                preview="BLDC Fan", port_layout={"left": ["power_in", "pwm_in"], "right": ["air_out"], "top": [], "bottom": ["mount"]}),
        ),
        component(
            component_type_id="industrial_blower",
            display_name="Industrial Blower",
            category="actuation_mechanical",
            description="High-flow blower for process ventilation and pneumatic feed.",
            physical_domain="electromechanical",
            tags=["blower", "airflow", "process"],
            ports=[
                port("power_in", "Power Input", "input", "dc_power", "voltage"),
                port("air_in", "Air Inlet", "input", "airflow", "airflow"),
                port("air_out", "Air Outlet", "output", "airflow", "airflow"),
                port("shaft_in", "Shaft Input", "input", "mechanical_rotation", "rpm", required=False),
            ],
            signal_templates=[
                signal("blower_airflow", "Blower Airflow", "airflow", "CFM", "air_out", expected_min=0, expected_max=500, alarm_low=100),
                signal("blower_pressure", "Blower Pressure", "pressure", "inH2O", "air_out", expected_min=0, expected_max=20, alarm_low=2),
                signal("blower_vibration", "Blower Vibration", "vibration", "mm/s", "air_out", expected_min=0, expected_max=12, alarm_high=8),
                signal("blower_current", "Blower Current", "current", "A", "power_in", expected_min=0, expected_max=15, alarm_high=13),
            ],
            fault_modes=[
                fault("inlet_blockage", "Inlet Blockage", "Restricted inlet reduces flow.", "warning",
                      ["Inspect blower inlet guard and remove obstruction after isolating power."],
                      required_evidence=[ev("blower_airflow", "low")]),
                fault("outlet_restriction", "Outlet Restriction", "Downstream damper or duct collapse limits flow.", "warning",
                      ["Verify damper position and duct integrity.", "Check filter differential across blower path."]),
                fault("weak_output", "Weak Output", "Blower cannot reach design flow at rated speed.", "warning",
                      ["Measure current and RPM under load.", "Inspect impeller for wear or fouling."]),
                fault("vibration_imbalance", "Vibration Imbalance", "Impeller imbalance causes elevated vibration.", "critical",
                      ["Schedule impeller inspection and balancing.", "Reduce speed until vibration within limits."],
                      required_evidence=[ev("blower_vibration", "high")], safety="caution"),
            ],
            recommended_sensors=["airflow_sensor", "pressure_sensor", "vibration_sensor", "current_sensor"],
            limits={"max_airflow_cfm": 500, "max_current_a": 15},
            visual_asset=visual("blower", accent_role="actuation", node_shape="rect_card", low_poly="box_with_impeller",
                                preview="Blower", port_layout={"left": ["air_in", "power_in"], "right": ["air_out"], "top": ["shaft_in"], "bottom": ["mount"]}),
        ),
        component(
            component_type_id="pump",
            display_name="Centrifugal Pump",
            category="actuation_mechanical",
            description="Fluid mover for coolant, process, and tank transfer loops.",
            physical_domain="fluid",
            tags=["pump", "fluid", "process"],
            ports=[
                port("power_in", "Power Input", "input", "dc_power", "voltage"),
                port("fluid_in", "Fluid Inlet", "input", "fluid_flow", "data"),
                port("fluid_out", "Fluid Outlet", "output", "fluid_flow", "data"),
                port("shaft_in", "Shaft Input", "input", "mechanical_rotation", "rpm"),
            ],
            signal_templates=[
                signal("pump_flow", "Pump Flow", "data", "L/min", "fluid_out", expected_min=0, expected_max=60, alarm_low=5),
                signal("pump_current", "Pump Current", "current", "A", "power_in", expected_min=0, expected_max=6, alarm_high=5.5),
                signal("pump_pressure", "Discharge Pressure", "pressure", "psi", "fluid_out", expected_min=0, expected_max=80, alarm_low=10),
            ],
            fault_modes=[
                fault("dry_run", "Dry Run", "Pump operates without adequate fluid.", "critical",
                      ["Shut down immediately and verify suction level.", "Prime pump before restart per procedure."],
                      required_evidence=[ev("pump_flow", "low"), ev("pump_current", "low")], safety="stop_required"),
                fault("clogged_impeller", "Clogged Impeller", "Debris restricts impeller passage.", "warning",
                      ["Isolate and inspect impeller housing.", "Install strainer upstream if debris is recurring."]),
                fault("cavitation", "Cavitation", "Vapor bubbles form due to low NPSH.", "warning",
                      ["Verify suction head and fluid temperature.", "Reduce speed until cavitation noise subsides."]),
                fault("low_flow", "Low Flow", "Flow below process requirement.", "warning",
                      ["Check valve positions and filter restriction.", "Verify motor speed and impeller condition."],
                      required_evidence=[ev("pump_flow", "low")]),
            ],
            recommended_sensors=["pressure_sensor", "current_sensor"],
            limits={"max_flow_lpm": 60},
            visual_asset=visual("pump", accent_role="actuation", node_shape="hex_card", low_poly="volute_housing",
                                preview="Pump", port_layout={"left": ["fluid_in", "power_in"], "right": ["fluid_out"], "top": ["shaft_in"], "bottom": ["mount"]}),
        ),
        component(
            component_type_id="solenoid_valve",
            display_name="Solenoid Valve",
            category="actuation_mechanical",
            description="Electrically actuated valve for fluid or pneumatic routing.",
            physical_domain="fluid",
            tags=["valve", "solenoid", "fluid"],
            ports=[
                port("coil_in", "Coil Drive", "input", "digital_signal", "boolean_state"),
                port("fluid_in", "Fluid Inlet", "bidirectional", "fluid_flow", "data"),
                port("fluid_out", "Fluid Outlet", "bidirectional", "fluid_flow", "data"),
            ],
            signal_templates=[
                signal("valve_state", "Valve State", "boolean_state", "bool", "coil_in", expected_min=0, expected_max=1),
                signal("valve_flow", "Valve Flow", "data", "L/min", "fluid_out", expected_min=0, expected_max=30),
            ],
            fault_modes=[
                fault("stuck_open", "Stuck Open", "Valve remains open when commanded closed.", "critical",
                      ["Isolate upstream pressure before service.", "Replace valve assembly if coil de-energized but flow continues."],
                      safety="isolate_before_touch"),
                fault("stuck_closed", "Stuck Closed", "Valve will not open when commanded.", "warning",
                      ["Verify coil voltage during commanded open.", "Inspect for debris on seat and plunger."]),
            ],
            recommended_sensors=["pressure_sensor"],
            limits={"max_pressure_psi": 150},
            visual_asset=visual("valve", accent_role="actuation", node_shape="narrow_card", low_poly="valve_body",
                                preview="Solenoid", port_layout={"left": ["fluid_in", "coil_in"], "right": ["fluid_out"], "top": [], "bottom": ["mount"]}),
        ),
        component(
            component_type_id="belt_coupling",
            display_name="Belt Coupling",
            category="actuation_mechanical",
            description="Flexible belt drive between motor shaft and driven equipment.",
            physical_domain="mechanical",
            tags=["coupling", "belt", "drive"],
            ports=[
                port("shaft_in", "Input Shaft", "input", "mechanical_rotation", "rpm"),
                port("shaft_out", "Output Shaft", "output", "mechanical_rotation", "rpm"),
            ],
            signal_templates=[
                signal("coupling_slip_ratio", "Slip Ratio", "data", "%", "shaft_out", expected_min=0, expected_max=5, alarm_high=4),
            ],
            fault_modes=[
                fault("belt_slip", "Belt Slip", "Belt slips under torque load.", "warning",
                      ["Check belt tension per manufacturer spec.", "Inspect for glaze or oil contamination on pulley."]),
                fault("belt_wear", "Belt Wear", "Visible cracking or fraying on belt.", "warning",
                      ["Replace belt before complete failure.", "Verify pulley alignment to prevent edge wear."]),
            ],
            recommended_sensors=["rpm_tachometer"],
            limits={"max_rpm": 3600},
            visual_asset=visual("coupling", accent_role="actuation", node_shape="link_card", low_poly="dual_pulley",
                                preview="Belt", port_layout={"left": ["shaft_in"], "right": ["shaft_out"], "top": [], "bottom": ["mount"]}),
        ),
        component(
            component_type_id="bearing_block",
            display_name="Bearing Block",
            category="actuation_mechanical",
            description="Shaft support bearing for motor and fan assemblies.",
            physical_domain="mechanical",
            tags=["bearing", "support", "mechanical"],
            ports=[
                port("shaft_in", "Shaft Through", "bidirectional", "mechanical_rotation", "rpm"),
                port("mount", "Mount", "input", "mounting", "physical_mount"),
            ],
            signal_templates=[
                signal("bearing_temp", "Bearing Temperature", "temperature", "C", "shaft_in", expected_min=20, expected_max=90, alarm_high=70),
                signal("bearing_vibration", "Bearing Vibration", "vibration", "mm/s", "shaft_in", expected_min=0, expected_max=8, alarm_high=5),
            ],
            fault_modes=[
                fault("lubrication_loss", "Lubrication Loss", "Insufficient lubricant causes heat and wear.", "warning",
                      ["Verify grease interval and quantity.", "Inspect for seal leak at bearing housing."]),
                fault("race_damage", "Race Damage", "Pitting or spalling on bearing race.", "critical",
                      ["Reduce speed and schedule replacement.", "Analyze vibration spectrum for bearing defect frequencies."],
                      required_evidence=[ev("bearing_vibration", "high")]),
            ],
            recommended_sensors=["vibration_sensor", "temperature_sensor"],
            limits={"max_rpm": 3600},
            visual_asset=visual("bearing", accent_role="actuation", node_shape="square_card", low_poly="pillow_block",
                                preview="Bearing", port_layout={"left": ["shaft_in"], "right": [], "top": [], "bottom": ["mount"]}),
        ),
        component(
            component_type_id="air_duct",
            display_name="Air Duct",
            category="process_physical",
            description="Conducts airflow between blower, fan, and process zones.",
            physical_domain="airflow",
            tags=["duct", "airflow", "process"],
            ports=[
                port("air_in", "Air Inlet", "input", "airflow", "airflow"),
                port("air_out", "Air Outlet", "output", "airflow", "airflow"),
            ],
            signal_templates=[],
            fault_modes=[
                fault("duct_blockage", "Duct Blockage", "Obstruction reduces cross-sectional flow area.", "warning",
                      ["Inspect access panels for debris or collapsed liner.", "Verify damper not partially closed downstream."]),
                fault("duct_leak", "Duct Leak", "Leak at joint reduces delivered airflow.", "warning",
                      ["Pressurize section and locate leak with smoke pencil.", "Reseal joint with rated duct sealant."]),
                fault("flow_restriction", "Flow Restriction", "Gradual restriction from contamination.", "warning",
                      ["Measure differential pressure across duct segment.", "Schedule cleaning if DP exceeds baseline."]),
            ],
            recommended_sensors=["airflow_sensor", "pressure_sensor"],
            limits={"max_velocity_fpm": 2500},
            visual_asset=visual("duct", accent_role="process", node_shape="channel_card", low_poly="rect_channel",
                                preview="Air Duct", port_layout={"left": ["air_in"], "right": ["air_out"], "top": [], "bottom": []}),
        ),
        component(
            component_type_id="fluid_pipe",
            display_name="Fluid Pipe",
            category="process_physical",
            description="Rigid pipe segment for fluid transfer between pump and tank.",
            physical_domain="fluid",
            tags=["pipe", "fluid", "process"],
            ports=[
                port("fluid_in", "Fluid Inlet", "input", "fluid_flow", "data"),
                port("fluid_out", "Fluid Outlet", "output", "fluid_flow", "data"),
            ],
            signal_templates=[],
            fault_modes=[
                fault("pipe_leak", "Pipe Leak", "Fluid escape at fitting or wall.", "critical",
                      ["Isolate segment and depressurize before repair.", "Replace compromised section if wall thinning detected."],
                      safety="isolate_before_touch"),
                fault("partial_blockage", "Partial Blockage", "Scale or debris reduces effective diameter.", "warning",
                      ["Flush segment per maintenance procedure.", "Inspect upstream strainer condition."]),
            ],
            recommended_sensors=["pressure_sensor"],
            limits={"max_pressure_psi": 200},
            visual_asset=visual("pipe", accent_role="process", node_shape="channel_card", low_poly="cylinder_segment",
                                preview="Pipe", port_layout={"left": ["fluid_in"], "right": ["fluid_out"], "top": [], "bottom": []}),
        ),
        component(
            component_type_id="tank_reservoir",
            display_name="Tank Reservoir",
            category="process_physical",
            description="Storage vessel for coolant or process fluid inventory.",
            physical_domain="fluid",
            tags=["tank", "reservoir", "storage"],
            ports=[
                port("fluid_in", "Fill Inlet", "input", "fluid_flow", "data"),
                port("fluid_out", "Outlet", "output", "fluid_flow", "data"),
                port("vent", "Vent", "output", "pneumatic_air", "pressure", required=False),
            ],
            signal_templates=[
                signal("tank_level", "Tank Level", "data", "%", "fluid_out", expected_min=10, expected_max=95, alarm_low=15, alarm_high=90),
            ],
            fault_modes=[
                fault("low_level", "Low Level", "Fluid inventory below minimum operating level.", "warning",
                      ["Verify inlet supply and valve positions.", "Add fluid per specification before resuming pump operation."],
                      required_evidence=[ev("tank_level", "low")]),
                fault("overfill_risk", "Overfill Risk", "Level approaching maximum safe fill.", "warning",
                      ["Close fill valve and verify overflow path.", "Check level sensor calibration against manual gauge."]),
            ],
            recommended_sensors=["pressure_sensor"],
            limits={"capacity_l": 200},
            visual_asset=visual("tank", accent_role="process", node_shape="tall_card", low_poly="cylinder_vessel",
                                preview="Tank", port_layout={"left": ["fluid_in"], "right": ["fluid_out"], "top": ["vent"], "bottom": ["mount"]}),
        ),
        component(
            component_type_id="filter_mesh_restriction",
            display_name="Filter Mesh Restriction",
            category="process_physical",
            description="Mesh or cartridge filter introducing controlled flow restriction.",
            physical_domain="fluid",
            tags=["filter", "restriction", "process"],
            ports=[
                port("flow_in", "Flow Inlet", "input", "fluid_flow", "data"),
                port("flow_out", "Flow Outlet", "output", "fluid_flow", "data"),
            ],
            signal_templates=[
                signal("filter_dp", "Filter Differential Pressure", "pressure", "psi", "flow_out", expected_min=0, expected_max=15, alarm_high=12),
            ],
            fault_modes=[
                fault("partial_blockage", "Partial Blockage", "Accumulated debris increases pressure drop.", "warning",
                      ["Compare DP to clean baseline.", "Replace or clean filter element per schedule."],
                      required_evidence=[ev("filter_dp", "high")]),
                fault("full_blockage", "Full Blockage", "Flow effectively blocked through filter.", "critical",
                      ["Stop upstream pump to prevent damage.", "Replace filter element before restart."],
                      required_evidence=[ev("filter_dp", "high")], safety="stop_required"),
                fault("contamination_buildup", "Contamination Buildup", "Gradual fouling without sudden blockage.", "warning",
                      ["Trend DP over operating hours.", "Advance maintenance interval if slope exceeds baseline."]),
            ],
            recommended_sensors=["pressure_sensor"],
            limits={"max_dp_psi": 15},
            visual_asset=visual("filter", accent_role="process", node_shape="rect_card", low_poly="mesh_panel",
                                preview="Filter", port_layout={"left": ["flow_in"], "right": ["flow_out"], "top": [], "bottom": []}),
        ),
        component(
            component_type_id="current_sensor",
            display_name="Current Sensor",
            category="sensors",
            description="Hall or shunt-based current measurement for motor and supply monitoring.",
            physical_domain="electrical",
            tags=["sensor", "current", "measurement"],
            ports=[
                port("sense_in", "Current Loop", "input", "dc_power", "current"),
                port("signal_out", "Analog Output", "output", "analog_signal", "current"),
            ],
            signal_templates=[
                signal("measured_current", "Measured Current", "current", "A", "signal_out", expected_min=0, expected_max=20),
            ],
            fault_modes=[
                fault("missing_signal", "Missing Signal", "No output from sensor.", "warning",
                      ["Verify excitation and loop power.", "Check wiring continuity to analog input."]),
                fault("stale_signal", "Stale Signal", "Value frozen despite load change.", "warning",
                      ["Compare against second measurement path.", "Replace sensor if frozen under known load step."]),
                fault("noisy_signal", "Noisy Signal", "Excessive electrical noise on output.", "warning",
                      ["Route cable away from motor leads.", "Add ferrite and verify shield ground at one end only."]),
            ],
            recommended_sensors=[],
            limits={"max_range_a": 20},
            visual_asset=visual("current_sensor", accent_role="sensor", node_shape="small_card", low_poly="sensor_chip",
                                preview="I Sensor", port_layout={"left": ["sense_in"], "right": ["signal_out"], "top": [], "bottom": ["mount"]}),
        ),
        component(
            component_type_id="voltage_sensor",
            display_name="Voltage Sensor",
            category="sensors",
            description="Divider or isolated voltage measurement for bus monitoring.",
            physical_domain="electrical",
            tags=["sensor", "voltage", "measurement"],
            ports=[
                port("sense_in", "Voltage Tap", "input", "dc_power", "voltage"),
                port("signal_out", "Analog Output", "output", "analog_signal", "voltage"),
            ],
            signal_templates=[
                signal("measured_voltage", "Measured Voltage", "voltage", "V", "signal_out", expected_min=0, expected_max=48),
            ],
            fault_modes=[
                fault("missing_signal", "Missing Signal", "No voltage reading present.", "warning",
                      ["Verify tap connection and fuse upstream.", "Measure raw voltage at terminals with DMM."]),
                fault("impossible_reading", "Impossible Reading", "Reading outside physical possibility.", "warning",
                      ["Check scaling and ADC range in PLC.", "Inspect for short on sense leads."]),
            ],
            recommended_sensors=[],
            limits={"max_range_v": 48},
            visual_asset=visual("voltage_sensor", accent_role="sensor", node_shape="small_card", low_poly="sensor_chip",
                                preview="V Sensor", port_layout={"left": ["sense_in"], "right": ["signal_out"], "top": [], "bottom": ["mount"]}),
        ),
        component(
            component_type_id="rpm_tachometer",
            display_name="RPM Tachometer",
            category="sensors",
            description="Rotational speed sensor for shafts and fan hubs.",
            physical_domain="mechanical",
            tags=["sensor", "rpm", "tachometer"],
            ports=[
                port("shaft_sense", "Shaft Sense", "input", "mechanical_rotation", "rpm"),
                port("signal_out", "Pulse Output", "output", "digital_signal", "rpm"),
            ],
            signal_templates=[
                signal("measured_rpm", "Measured RPM", "rpm", "rpm", "signal_out", expected_min=0, expected_max=6000),
            ],
            fault_modes=[
                fault("missing_signal", "Missing Signal", "No pulses detected.", "warning",
                      ["Verify sensor gap to target wheel.", "Inspect connector for intermittent contact."]),
                fault("stuck_value", "Stuck Value", "RPM reading constant despite speed change.", "warning",
                      ["Swap channel to confirm sensor vs input fault.", "Clean optical or magnetic target surface."]),
            ],
            recommended_sensors=[],
            limits={"max_rpm": 6000},
            visual_asset=visual("rpm_sensor", accent_role="sensor", node_shape="small_card", low_poly="disc_sensor",
                                preview="RPM", port_layout={"left": ["shaft_sense"], "right": ["signal_out"], "top": [], "bottom": ["mount"]}),
        ),
        component(
            component_type_id="vibration_sensor",
            display_name="Vibration Sensor",
            category="sensors",
            description="Accelerometer or velocity probe for rotating equipment health.",
            physical_domain="mechanical",
            tags=["sensor", "vibration", "condition"],
            ports=[
                port("mount_sense", "Mount Point", "input", "mounting", "vibration"),
                port("signal_out", "Analog Output", "output", "analog_signal", "vibration"),
            ],
            signal_templates=[
                signal("measured_vibration", "Measured Vibration", "vibration", "mm/s", "signal_out", expected_min=0, expected_max=25, alarm_high=10),
            ],
            fault_modes=[
                fault("missing_signal", "Missing Signal", "No vibration data received.", "warning",
                      ["Verify sensor power and cable integrity.", "Re-seat mount bolt to rated torque."]),
                fault("noisy_signal", "Noisy Signal", "Signal dominated by electrical or structural noise.", "warning",
                      ["Confirm sensor mounted on rigid surface.", "Filter out known structural resonance in analysis."]),
            ],
            recommended_sensors=[],
            limits={"max_range_mm_s": 25},
            visual_asset=visual("vibration_sensor", accent_role="sensor", node_shape="small_card", low_poly="probe_block",
                                preview="Vibe", port_layout={"left": ["mount_sense"], "right": ["signal_out"], "top": [], "bottom": ["mount"]}),
        ),
        component(
            component_type_id="temperature_sensor",
            display_name="Temperature Sensor",
            category="sensors",
            description="RTD or thermistor for motor, bearing, and fluid temperature.",
            physical_domain="thermal",
            tags=["sensor", "temperature", "thermal"],
            ports=[
                port("thermal_sense", "Thermal Contact", "input", "thermal", "temperature"),
                port("signal_out", "Analog Output", "output", "analog_signal", "temperature"),
            ],
            signal_templates=[
                signal("measured_temperature", "Measured Temperature", "temperature", "C", "signal_out", expected_min=-20, expected_max=150, alarm_high=85),
            ],
            fault_modes=[
                fault("missing_signal", "Missing Signal", "Open circuit on temperature loop.", "warning",
                      ["Inspect lead wire at termination.", "Verify excitation current on RTD loop."]),
                fault("impossible_reading", "Impossible Reading", "Reading outside installed range.", "warning",
                      ["Check sensor type configuration in PLC.", "Verify sensor seated on heat source."]),
            ],
            recommended_sensors=[],
            limits={"max_range_c": 150},
            visual_asset=visual("temp_sensor", accent_role="sensor", node_shape="small_card", low_poly="probe_stem",
                                preview="Temp", port_layout={"left": ["thermal_sense"], "right": ["signal_out"], "top": [], "bottom": ["mount"]}),
        ),
        component(
            component_type_id="airflow_sensor",
            display_name="Airflow Sensor",
            category="sensors",
            description="Hot-wire or differential sensor for duct and blower airflow.",
            physical_domain="airflow",
            tags=["sensor", "airflow", "hvac"],
            ports=[
                port("air_sense", "Air Stream", "input", "airflow", "airflow"),
                port("signal_out", "Analog Output", "output", "analog_signal", "airflow"),
            ],
            signal_templates=[
                signal("measured_airflow", "Measured Airflow", "airflow", "CFM", "signal_out", expected_min=0, expected_max=600),
            ],
            fault_modes=[
                fault("missing_signal", "Missing Signal", "No airflow reading.", "warning",
                      ["Verify sensor seated in flow path.", "Check for ice or debris on probe element."]),
                fault("stale_signal", "Stale Signal", "Reading unchanged during known flow change.", "warning",
                      ["Command blower speed step and verify response.", "Recalibrate sensor span if drift confirmed."]),
            ],
            recommended_sensors=[],
            limits={"max_range_cfm": 600},
            visual_asset=visual("airflow_sensor", accent_role="sensor", node_shape="small_card", low_poly="flow_probe",
                                preview="Airflow", port_layout={"left": ["air_sense"], "right": ["signal_out"], "top": [], "bottom": ["mount"]}),
        ),
        component(
            component_type_id="pressure_sensor",
            display_name="Pressure Sensor",
            category="sensors",
            description="Gauge or differential pressure transducer for fluid and air systems.",
            physical_domain="fluid",
            tags=["sensor", "pressure", "transducer"],
            ports=[
                port("pressure_tap", "Pressure Tap", "input", "fluid_flow", "pressure"),
                port("signal_out", "Analog Output", "output", "analog_signal", "pressure"),
            ],
            signal_templates=[
                signal("measured_pressure", "Measured Pressure", "pressure", "psi", "signal_out", expected_min=0, expected_max=200),
            ],
            fault_modes=[
                fault("missing_signal", "Missing Signal", "No pressure output.", "warning",
                      ["Verify tap not plugged.", "Inspect transmitter power and 4-20mA loop."]),
                fault("stuck_value", "Stuck Value", "Pressure frozen during system change.", "warning",
                      ["Vent tap and verify response.", "Replace transducer if diaphragm suspected seized."]),
            ],
            recommended_sensors=[],
            limits={"max_range_psi": 200},
            visual_asset=visual("pressure_sensor", accent_role="sensor", node_shape="small_card", low_poly="transducer_block",
                                preview="Pressure", port_layout={"left": ["pressure_tap"], "right": ["signal_out"], "top": [], "bottom": ["mount"]}),
        ),
        component(
            component_type_id="limit_switch",
            display_name="Limit Switch",
            category="sensors",
            description="Mechanical or proximity switch for end-of-travel and guard interlock.",
            physical_domain="mechanical",
            tags=["sensor", "limit", "interlock"],
            ports=[
                port("actuator_in", "Actuator Input", "input", "mounting", "boolean_state"),
                port("signal_out", "Contact Output", "output", "digital_signal", "boolean_state"),
            ],
            signal_templates=[
                signal("switch_state", "Switch State", "boolean_state", "bool", "signal_out", expected_min=0, expected_max=1),
            ],
            fault_modes=[
                fault("missing_signal", "Missing Signal", "No state transition when actuated.", "warning",
                      ["Verify actuator alignment and travel.", "Test contact continuity with meter."]),
                fault("stuck_value", "Stuck Value", "State does not change when released.", "warning",
                      ["Inspect for mechanical binding on lever.", "Replace switch if contact welded."]),
            ],
            recommended_sensors=[],
            limits={"max_actuations_per_min": 60},
            visual_asset=visual("limit_switch", accent_role="sensor", node_shape="small_card", low_poly="lever_switch",
                                preview="Limit SW", port_layout={"left": ["actuator_in"], "right": ["signal_out"], "top": [], "bottom": ["mount"]}),
        ),
    ]
    return {
        "library_id": "plantlens_standard_industrial_v1",
        "version": "1.0.0",
        "description": "Manufacturer-neutral industrial component templates for PlantLens assembly studio.",
        "components": components,
    }


def main() -> None:
    library = build_library()
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT.open("w", encoding="utf-8") as handle:
        json.dump(library, handle, indent=2)
        handle.write("\n")
    print(f"Wrote {len(library['components'])} components to {OUTPUT}")


if __name__ == "__main__":
    main()