"""HMI projection layer — strict contracts and bench payload adapter."""

from app.hmi.bench_adapter import (
    BenchAsset,
    BenchCausalityEdge,
    BenchPayload,
    BenchSignal,
    BenchSignalQuality,
    load_bench_payload,
)
from app.hmi.contracts import (
    AlarmGroup,
    AssetHMIState,
    CausalityEdgeHMI,
    DataQualityState,
    EvidenceItem,
    ExpectedRange,
    HMIAssetStatus,
    HMIBaseModel,
    HMIOverallStatus,
    HMISeverity,
    HMISignalStatus,
    IncidentHMIState,
    OperatorAction,
    PlantHMIState,
    RootCauseCandidate,
    SafetyLevel,
    SignalHMIState,
)

__all__ = [
    "AlarmGroup",
    "AssetHMIState",
    "BenchAsset",
    "BenchCausalityEdge",
    "BenchPayload",
    "BenchSignal",
    "BenchSignalQuality",
    "CausalityEdgeHMI",
    "DataQualityState",
    "EvidenceItem",
    "ExpectedRange",
    "HMIAssetStatus",
    "HMIBaseModel",
    "HMIOverallStatus",
    "HMISeverity",
    "HMISignalStatus",
    "IncidentHMIState",
    "OperatorAction",
    "PlantHMIState",
    "RootCauseCandidate",
    "SafetyLevel",
    "SignalHMIState",
    "load_bench_payload",
]