#!/usr/bin/env node
/**
 * Generates packages/icons/svg/<kind>.svg (stroke="currentColor", outline look) for every
 * SymbolKind from the shared geometry module, removes stale files, and rewrites the symbol table in
 * README.md. Needs Node >= 22.18 (native TypeScript type stripping); no dependencies.
 *
 *   node packages/icons/build-svg.mjs          # write
 *   node packages/icons/build-svg.mjs --check  # exit 1 if anything is out of date
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { SYMBOL_KINDS, SYMBOL_META, renderSymbolSvg } from "./render.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const svgDir = join(here, "svg");
const readmePath = join(here, "README.md");
const check = process.argv.includes("--check");

const SAMPLE_TAG = { sensor: "TT" };
const wanted = new Map(SYMBOL_KINDS.map((k) => [`${k}.svg`, renderSymbolSvg(k, { mode: "static", tag: SAMPLE_TAG[k] })]));

const stale = [];
const changed = [];
mkdirSync(svgDir, { recursive: true });
for (const f of readdirSync(svgDir)) if (f.endsWith(".svg") && !wanted.has(f)) stale.push(f);
for (const [f, body] of wanted) {
  const p = join(svgDir, f);
  if (!existsSync(p) || readFileSync(p, "utf8") !== body) changed.push(f);
}

const START = "<!-- symbols:start (generated by build-svg.mjs) -->";
const END = "<!-- symbols:end -->";
const rows = SYMBOL_KINDS.map((k) => `| <img src="svg/${k}.svg" width="32" alt=""> | \`${k}\` | ${SYMBOL_META[k].label} | ${SYMBOL_META[k].category} |`);
const table = `${START}\n| Symbol | Kind | Label | Category |\n|:--:|------|-------|----------|\n${rows.join("\n")}\n${END}`;
const readme = readFileSync(readmePath, "utf8");
const nextReadme = readme.includes(START)
  ? readme.slice(0, readme.indexOf(START)) + table + readme.slice(readme.indexOf(END) + END.length)
  : `${readme.trimEnd()}\n\n${table}\n`;

if (check) {
  const dirty = [...stale, ...changed, ...(nextReadme !== readme ? ["README.md"] : [])];
  if (dirty.length) {
    console.error(`icons out of date: ${dirty.join(", ")} — run node packages/icons/build-svg.mjs`);
    process.exit(1);
  }
  console.log(`icons up to date (${wanted.size} symbols)`);
} else {
  for (const f of stale) rmSync(join(svgDir, f));
  for (const f of changed) writeFileSync(join(svgDir, f), wanted.get(f));
  if (nextReadme !== readme) writeFileSync(readmePath, nextReadme);
  console.log(`wrote ${changed.length} svg, removed ${stale.length} stale, ${wanted.size} symbols total`);
}
